### ISSUE TITLE
Add arm64 image

### ISSUE THREAD

**Issue by chekist32** [kukymbr/goose-docker#4]
**Is your feature request related to a problem? Please describe.**

The current Docker Image doesn't support arm64 architecture, which causes compatibility issues on ARM-based systems.

**Describe the solution you'd like**

Refactor the Dockerfile to fetch the goose binary based on the arch, and probably refactor the CD workflow.

**Describe alternatives you've considered**

None.

**Additional context**

I have already added some code in the Dockerfile to fetch the particular binary based on the arch [here](https://github.com/chekist32/goose-docker/commit/de0c7b9b287995d6c5efde6fd775c81bf3c6de2a#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557).

**Comment by kukymbr** [comment]
Hi!
Seems useful, would you create a PR with these changes, please?

**Comment by chekist32** [comment]
@kukymbr should i also update the GitHub Workflows?

**Comment by kukymbr** [comment]
@chekist32 thank you for a PR, I've merged it. I'll add this change into the workflow and docs. Changes are available in the `latest` tag and will be contained in the next `v*` tag after the goose release.

#5

**Comment by kukymbr** [comment]
added to workflow & doc:

[AMD64/ARM64 architecture](https://github.com/kukymbr/goose-docker?tab=readme-ov-file#amd64arm64-architecture)

**Comment by chekist32** [comment]
In your `.github/workflows/push_ghcr.yml` you are actually building two AMD64 Docker images, but with different binaries.
```yaml
- name: Build image
  run: docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg TARGETARCH=${{ matrix.target_arch }} --label "runnumber=${GITHUB_RUN_ID}"
```
You should change it to something like this:
```diff
- --build-arg TARGETARCH=${{ matrix.target_arch }}"
+ --platform linux/${{ matrix.target_arch }}"
```
Additionally, you need to add this stage before the actual build stage in your workflow: 
```yaml
- name: Set up QEMU
  uses: docker/setup-qemu-action@v3

- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3
```

Btw, I don’t really understand why you're using two different workflows for basically the same task, because the only thing that differs between these workflows is the Docker registry.

And another remark, you can have an image with the different platforms/archs under a single tag. You don`t need to create a separate tag for each arch.
https://docs.docker.com/build/building/multi-platform/#difference-between-single-platform-and-multi-platform-images

**Comment by chekist32** [comment]
Here is an example GitHub workflow that builds a multi-platform image and pushes it to different registries.
https://docs.docker.com/build/ci/github-actions/push-multi-registries/
